import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        data-bs-theme="dark"
        className="bg-gray-900 text-gray-300 scroll-smooth overflow-x-hidden overflow-y-scroll"
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
